name: Push Backend to Deploy Repo
on:
  push:
    branches: [ master ]
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up remotes to Backend Deploy Repo
      run: |
        git remote add deploy https://github.com/watchpartyappmain/watchparty-server-deploy.git
        git fetch --all
        git checkout -b deploy-sync deploy/master
        git config --global user.email "watchpartyappmain@gmail.com"
        git config --global user.name "watchpartyappmain"
        git filter-branch --prune-empty --subdirectory-filter WatchParty/backend master
        git merge -X theirs master --allow-unrelated-histories 
        git fetch --unshallow origin
    - name: Push Backend to Deploy Repo
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.personal_github_token }}
        REPOSITORY: 'watchpartyappmain/watchparty-server-deploy'
        INPUT_BRANCH: 'master'
      run: |
        remote_repo="https://watchpartymainapp:${INPUT_GITHUB_TOKEN}@github.com/${REPOSITORY}.git"
        git push "${remote_repo}" HEAD:${INPUT_BRANCH} --follow-tags --force;
