# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Frontend and Server

on: [ push, pull_request ]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v2
    - name: Run test on backend
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd WatchParty/backend/
        npm install
        npm run test
      env:
        CI: true
  test_frontend:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v2
    - name: Run test on frontend
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd WatchParty/client/
        npm install
        npm run test
      env:
        CI: true
      
    
